### ISSUE TITLE
Audit PostCSS plugins

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#10]
I'm concerned that we're going too far with PostCSS plugins, and we're introducing. In particular:

- I don't love the px to rem thing. I don't see the issue with using rems directly. This just feels like more work for the build process with little benefit.
- From what I can tell, we don't need sanitize _and_ normalize. Looks like sanitize brings normalize with it. See here: https://csstools.github.io/sanitize.css/
- Can we bring in sanitize via a package instead of copying and pasting the code into the project? Then we can get rid of the lib directory.

**Comment by phritolay** [comment]
1. The `px-to-rem` package helps with consistency and from bugs when altering the font-size on the `body`. It also helps us move faster when our designs are in Photoshop, Sketch or InVision, without needing to calculate the units to rems. We're currently using Dart Sass with PostCSS plugins and both are written in JS and shouldn't effect the build process.

2. The `postcss-normalize` plugin allows us to specify if we'd like to use normalize or sanitize. We're only using sanitize, it's added in `src/styles/libs/sanitize.css` with`@import-sanitize;`. The great thing about using this package, is it utilizes the `.browserslistrc` file and only brings in the resets that are needed for our set of browsers.

3. Bringing sanitize in via a package would increase the file size for the reset stylesheet.

Let's discuss this a little more when you're in the office.

**Comment by seancdavis** [comment]
All good points. Closing.
