### ISSUE TITLE
Docz styles file location

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#11]
Does it make sense for the docz.scss file to be in the docs directory? It feels like it's floating out there by itself. Should it instead be grouped with the other global styles?

I don't know that there's a right answer here. It just feels a little odd hanging out where it is.

**Comment by phritolay** [comment]
I'm cool either way.  Let's also discuss this once you get in the office.

**Comment by seancdavis** [comment]
We decided we are going to move it into the `styles/lib` directory, and also move the documentation alongside it. This work is being done in #13.

It makes me wonder if we need the docs directory at all. If it's only going to house the single `index.mdx` file, maybe that file is `src/notes.mdx` or something like that. Either that, or maybe we make the README the index file for docs.

**Comment by seancdavis** [comment]
In #14 I decided to not use the README as the docs home page. It is kind of odd since it also has to function as a README for working with this library.

But I'll leave this open until we merge #13.
