### ISSUE TITLE
Add alias imports

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#127]
We could clean up our imports a bit by using [this](https://www.gatsbyjs.org/packages/gatsby-alias-imports/).

We'll likely have to do something with the Jest config to have specs run as well.

**Comment by phritolay** [comment]
I think this is a good idea to explore, but prior to implementing this we should look into if this will break auto complete in VS Code. I'm thinking it will and could slow us down.

**Comment by seancdavis** [comment]
Solved in #146.
