### ISSUE TITLE
Wire up header and footer to CMS

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#136]
This builds off of #129.

As part of this work, explore breaking up the link list component. The idea would be that the header and footer bring their own nav components as needed.

**Comment by phritolay** [comment]
#142 Will handle breaking up the `<LinkList />` component.

**Comment by seancdavis** [comment]
Make sure to include helper text in the CMS that describes behavior of the various fields.

**Comment by seancdavis** [comment]
When doing this, also add these items to the `schema.yml` file.
