### ISSUE TITLE
Add a carousel component

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#172]
Seems like we're constantly implementing a carousel. While their designs differ greatly, we could at least get rid of the boilerplate implementation and start with one right out of the box.

**Comment by seancdavis** [comment]
I've been working on a carousel for an 11ty site and realized that:

- Slick is dead
- Slick depends on jQuery

We should not be using Slick. We'd be upping our bundle size significantly to add an outdated tool.

My recommendation is that we look at something like [Swiper](https://swiperjs.com/react/). I've been using this and an happy with it so far. It's also the most active and well-supported one I could find among the modern options.

**Comment by phritolay** [comment]
@seancdavis We've been using [React Slick](https://react-slick.neostack.com) on other projects and it's a port of the jQuery version. I'm cool with looking into implementing Swiper and it does look well supported. 👍

**Comment by seancdavis** [comment]
Looks like it still [brings in jquery](https://github.com/akiran/react-slick/blob/master/package.json#L66) though.
