### ISSUE TITLE
Add Support for Contentful

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#183]
The starter currently only supports Forestry. We also want it to support Contentful. Since we are aligned on _pretty much only using Contentful and Forestry where possible_, we don't anticipate using another CMS in the future. However, we should consider it as a possibility.

Given that, the discussion here is about how we go about adding support for Contentful.

There is [a Gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/) that creates nodes from data within a Contentful space. We _could_ use this directly. However, we have an interesting scenario in front of us. The starter is built to support Forestry. That means that the foundation of the data (i.e. the data source) is not _actually_ Forestry, but markdown files committed to the repository. Therefore, we _theoretically_ already have a framework-agnostic means of sourcing data.

Given that, and in considering that we may want to work with more than Contentful in the future, I'm proposing that we build some sort of _glue_ layer between the Contentful plugin and our markdown files.

Pros to this approach:

- Interferes with the existing code to a minimal extent.
- (Theoretically) becomes trivial to swap out the CMS we want to use.
- Provides a solid and consistent foundation on which to include other API integrations in the future.

Cons:

- It could _up to_ double the number of nodes created from GraphQL queries. That will slow the build somewhat, but it also offloads that responsibility to the plugin. The extent to which that will affect the front-end performance is unknown.

The major features and adjustments that would take place for this body of work inlcude:

1. Provide a means to map Contentful queries to markdown file content
2. Adjust images to support use from local images as well as objects coming from Contentful

**Comment by dholloran-ample** [comment]
I like this, at first I was like well isn't this the responsibility of Gatsyb Source plugins but it doesn't look like there is a Forestry one since it's just Markdown. I know this is basically how Crossroads is set up and I can not think of a situation where it has been a hindrance. 

A few other Cons I see to this approach

1. (This could also be an upside) We will have to maintain it. Good for future integrations with other CMSs. Possibly bad if Contentful changes APIs.
1. A media-heavy site could fill up hard drive space locally. (Could be resolved by hosting media in Imgix which is how Crossroads works)

A few thoughts (Could be future considerations)

1. I am thinking it may be good as its own separate repo or at least make it a somewhat framework-agnostic toolkit that reads in an API and outputs Markdown to a configurable directory.
1. Allow for writing to JSON, YAML, MDX, Etc. via drivers. This would be a nice to have not really a need since you can do almost anything you need with Frontmatter.

All that said I'm on board with this it makes sense and seems like a more future proof solution

**Comment by seancdavis** [comment]
Thanks for the thoughts, @dholloran-ample!

> (This could also be an upside) We will have to maintain it. Good for future integrations with other CMSs. Possibly bad if Contentful changes APIs.

I agree. I think the trick here is that we're building the _glue_ between the source plugin and the output markdown files. I we can make this flexible, then _theoretically_ changes to the Contentful API would be absorbed by the source plugin and not the glue layer. That's a _Perfect World_ scenario. In the real world, we'd like have _something_ to change.

> A media-heavy site could fill up hard drive space locally. (Could be resolved by hosting media in Imgix which is how Crossroads works)

This is TBD in my mind. I _think_ the source plugin just uses their images API and doesn't download the images. I _think_. If that's the case, we don't have to worry about space. But we do have to run all necessary queries ahead of time and store the results in the markdown files. So the markdown files get a bit bulkier.

> I am thinking it may be good as its own separate repo or at least make it a somewhat framework-agnostic toolkit that reads in an API and outputs Markdown to a configurable directory.

I agree. It's kind of like what Stackbit seems to be doing with [Sourcebit](https://github.com/stackbithq/sourcebit). But ours would be much more opinionated — a way to map API data specifically to markdown files.

I like the idea of it being a separate library, and something we can promote. Let's get it working as a first-class citizen first, and then consider how we would pull it out.

> Allow for writing to JSON, YAML, MDX, Etc. via drivers. This would be a nice to have not really a need since you can do almost anything you need with Frontmatter.

Ah, interesting. I like this idea. I say we go the opinionated route first, but as we do, consider keeping the process open for less painful adjustments when we need to extend it.

**Comment by seancdavis** [comment]
We're going to pursue this work, but it will be as part of a client's body of work. Therefore, I'm putting it on hold for now.

**Comment by seancdavis** [comment]
I've removed the hold. We can start thinking about our next implementation and get support rolling. Here is the process I plan to take:

- [ ] Build a mechanism for retrieving content from Contentful. [This is a good starting point](https://github.com/seancdavis/everything-is-a-cms/blob/main/lib/import/contentful.js).
- [ ] Write the content to markdown files.
- [ ] Read from a configuration file to determine which content types and fields to pull down. Consider how they map to the directory/file to which they're written.
- [ ] Figure out associations.
- [ ] Normalize any discrepancies with the current markdown structure.
- [ ] Implement a 1:1 example.
- [ ] Be able to choose Contentful or Forestry and not have both lingering around.
- [ ] Documentation the process of setting up a CMS for a new project.
