### ISSUE TITLE
Create reference pages for global styles

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#2]
Create default doc pages for the following topics:

- [ ] Typography
- [ ] Global sass variables (colors, fonts, etc.)
- [ ] Utility classes
- [ ] Utility JS methods

Anything else?

**Comment by phritolay** [comment]
I'm currently working through Global Colors.

**Comment by seancdavis** [comment]
The more I thought about this, the more I realize that our approach to #105 is sound and we don't meed to pursue something like this.

Anything that shows up on screen does so via a layout or component. Therefore, there is little benefit to seeing global styles, but more benefit to seeing how the components and static templates are rendered, as that is ultimately what will show up on screen.

Regarding sass variables, utilities, and colors, developers are more than capable of looking at the appropriate file to see what is available to them. What we really should do is document how we've structured the styles directory, so we can point devs in the right direction.

That said, I'm going to close this. We do need to look into a better solution for documentation, understanding the nuance in the difference between the dev playbook and in-project documentation. But I'll create a new issue to handle that.
