### ISSUE TITLE
fix gatsby-remark-ample console warnings

### ISSUE THREAD

**Issue by phritolay** [ample/gatsby-starter-ample#201]
```
warn Plugin `gatsby-remark-ample` has customized the GraphQL type `SeoMeta`, which has already been
warn Plugin `gatsby-remark-ample` has customized the GraphQL type `Page`, which has already been defined
```

**Comment by seancdavis** [comment]
This one is on me. The gatsby-remark-ample plugin originally specifies these types, and then we're adding project-specific fields via the schema plugin. This feels like it's going to take some exploration. I want to minimize the extent to which these plugins are dependent on one another, but we'd also ideally define each type only once throughout the app.
