### ISSUE TITLE
Update configuration for next major release

### ISSUE THREAD

**Issue by phritolay** [ample/gatsby-starter-ample#30]
`warning Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.`

**Comment by seancdavis** [comment]
@phritolay I'm not sure that this is something we have control over, is it? We're not configuring yargs in our `package.json` file. I'm guessing it's coming from a library we're using. Not sure we want to spend the time to figure that out. But if you know more than I do, let me know.

**Comment by phritolay** [comment]
I looked into this little more and you're correct it's coming from a couple libraries we're using.
