### ISSUE TITLE
Debug Media Queries is not working

### ISSUE THREAD

**Issue by phritolay** [ample/gatsby-starter-ample#54]
**Describe the bug**
When trying to Debug Media Queries I'm getting the error in the screenshot below. I was receiving this same error while working locally with [gatsby-theme-ample-components](https://github.com/ample/gatsby-theme-ample-components) `<DebugMediaQueries />`, because there were conflicts between the project and the CL versions of react.

**To Reproduce**
1. Run `yarn run develop:debug`
2. Go to  'http://localhost:8000'

**Expected behavior**
The site should run properly and the `<DebugMediaQueries />` component should render in the bottom left hand corner of the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/1730906/80208284-e0070d00-85fd-11ea-8598-027ead2877a2.png)

**Comment by seancdavis** [comment]
We're solving this by going a different direction with this component. It will be moved into a local plugin per #89.
