### ISSUE TITLE
Let's have Jest ignore the `lib` directory

### ISSUE THREAD

**Issue by phritolay** [ample/gatsby-starter-ample#55]
**Describe the bug**
VS Code's Jest extension is pickup up the `lib` directory and either has failing tests or creates new snapshots.

**To Reproduce**
1. Run the jest runner in VS Code.

**Expected behavior**
The `lib` directory is ignored.

**Screenshots**
<image src="https://user-images.githubusercontent.com/1730906/80209552-4db43880-8600-11ea-8dcf-d554c413eac4.png" width="300px" />

**Comment by seancdavis** [comment]
@phritolay This is only an issue when running jest directly. What I'd prefer we do is run our scripts through package.json. Running this:

    $ yarn test

Will run the specs only against the `src` directory, effectively avoiding the issue you're seeing here. That said, I don't have a problem with ignoring the directory, so I'm going to merge #56.
