### ISSUE TITLE
How can we make it easier to update specs?

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#77]
I find myself consistently fixing broken builds simply by updating snapshots. What's the right course of action to helping us work more efficiently, while also making sure we have a passing test suite?

**Comment by phritolay** [comment]
A couple things that have helped on another project was adding `yarn run test:update` to the `develop` and `storybook` package scripts. I also use this [Jest extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) for VS Code. With both of these combined, I find myself in that situation less. The scripts help catch failing tests when starting the project and the extension keeps Jest running in the background and has popups asking if you'd like to update a snapshot when a component changes.

**Comment by seancdavis** [comment]
I really like [the approach here](https://www.mrozilla.cz/blog/gatsby-eslint-vscode-import-alias/). It leaves out what we'll likely have to address with Jest, but it may be worth it.

**Comment by seancdavis** [comment]
@phritolay Do you feel like your work in #186 effectively solves this?
